apiVersion: v1
kind: Service
metadata:
  name: fts-auth
  labels:
    app: fts-auth
spec:
  selector:
    app: fts-auth
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
